export const HOMEPAGE = '/home'
export const ALLTEAMS = '/allteams'
export const LOGIN = '/login'
export const MYTEAMS = '/myteams'
export const POKEDEX = '/pokedex'
export const ADDTEAM = '/addteam'
export const SIGNUP = '/signup'
export const LOGOUT = '/logout'
